[package]
name = "amitabha"
version = "0.1.0"
edition = "2021"
default-run = "amitabha"

[dependencies]
glam = { version = "0.27.0" }
sefirot = { path = "../sefirot/sefirot", features = ["glam", "trace"] }
sefirot_testbed = { path = "../sefirot/testbed" }
image = "0.25.5"
