[package]
name = "amitabha"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.27.0" }
sefirot = { path = "../sefirot/sefirot", features = ["glam"] }
sefirot_testbed = { path = "../sefirot/testbed" }
