[package]
name = "amitabha"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.30.5" }
keter = { git = "https://github.com/entropylost/sefirot", features = [
    "glam",
    "trace",
] }
keter_testbed = { git = "https://github.com/entropylost/sefirot" }
